### ISSUE TITLE
dkms install dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a fails

### ISSUE THREAD

**Issue by sschamp** [seflerZ/oneclick-gpu-pv#5]
`dkms install dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a`

```
CONFIG_DXGKRNL=m make -C /lib/modules/6.5.0-35-generic/build M=/var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build EXTRA_CFLAGS='-DCONFIG_DXGKRNL=m -include /var/lib
/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/extra-defines.h' modules...(bad exit status: 2)
ERROR (dkms apport): binary package for dxgkrnl: 5.6.rc2.r77380.g918dbaa9fa4a not found
Error! Bad return status for module build on kernel: 6.5.0-35-generic (x86_64)
Consult /var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/make.log for more information.
modprobe: FATAL: Module dxgkrnl not found in directory /lib/modules/6.5.0-35-generic
```

```
# cat /var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/make.log
DKMS make.log for dxgkrnl-5.6.rc2.r77380.g918dbaa9fa4a for kernel 6.5.0-35-generic (x86_64)
do 23 mei 2024 18:09:26 CEST
make: Entering directory '/usr/src/linux-headers-6.5.0-35-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  CC [M]  /var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.o
/var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.c: In function ‘dxg_probe_vmbus’:
/var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.c:765:13: error: implicit declaration of function ‘uuid_le_cmp’ [-Werror=implicit-function-declaration]
  765 |         if (uuid_le_cmp(hdev->dev_type, dxg_vmbus_id_table[0].guid) == 0) {
      |             ^~~~~~~~~~~
/var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.c: At top level:
/var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.c:852:29: error: initialization of ‘void (*)(struct hv_device *)’ from incompatible pointer type ‘int (*)(struct hv_device *)’ [-Werror=incompatible-pointer-types]
  852 |         .vmbus_drv.remove = dxg_remove_vmbus,
      |                             ^~~~~~~~~~~~~~~~
/var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.c:852:29: note: (near initialization for ‘dxgdrv.vmbus_drv.remove’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:251: /var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.5.0-35-generic/Makefile:2039: /var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build] Error 2
make: *** [Makefile:234: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.5.0-35-generic'
```

**Comment by seflerZ** [comment]
This is because you’re using kernel 6.5.0-35. The uploaded script (dxgkrnl) only supports kernel 5.6. You can to go to here to download versions matches your kernel.

从 Windows 版邮件发送

发件人: sschamp
发送时间: 2024年5月24日 0:11
收件人: seflerZ/oneclick-gpu-pv
抄送: Subscribed
主题: [seflerZ/oneclick-gpu-pv] dkms installdxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a fails (Issue #5)

dkms install dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a
CONFIG_DXGKRNL=m make -C /lib/modules/6.5.0-35-generic/build M=/var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build EXTRA_CFLAGS='-DCONFIG_DXGKRNL=m -include /var/lib
/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/extra-defines.h' modules...(bad exit status: 2)
ERROR (dkms apport): binary package for dxgkrnl: 5.6.rc2.r77380.g918dbaa9fa4a not found
Error! Bad return status for module build on kernel: 6.5.0-35-generic (x86_64)
Consult /var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/make.log for more information.
modprobe: FATAL: Module dxgkrnl not found in directory /lib/modules/6.5.0-35-generic
# cat /var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/make.log
DKMS make.log for dxgkrnl-5.6.rc2.r77380.g918dbaa9fa4a for kernel 6.5.0-35-generic (x86_64)
do 23 mei 2024 18:09:26 CEST
make: Entering directory '/usr/src/linux-headers-6.5.0-35-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
  CC [M]  /var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.o
/var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.c: In function ‘dxg_probe_vmbus’:
/var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.c:765:13: error: implicit declaration of function ‘uuid_le_cmp’ [-Werror=implicit-function-declaration]
  765 |         if (uuid_le_cmp(hdev->dev_type, dxg_vmbus_id_table[0].guid) == 0) {
      |             ^~~~~~~~~~~
/var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.c: At top level:
/var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.c:852:29: error: initialization of ‘void (*)(struct hv_device *)’ from incompatible pointer type ‘int (*)(struct hv_device *)’ [-Werror=incompatible-pointer-types]
  852 |         .vmbus_drv.remove = dxg_remove_vmbus,
      |                             ^~~~~~~~~~~~~~~~
/var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.c:852:29: note: (near initialization for ‘dxgdrv.vmbus_drv.remove’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:251: /var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build/dxgmodule.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.5.0-35-generic/Makefile:2039: /var/lib/dkms/dxgkrnl/5.6.rc2.r77380.g918dbaa9fa4a/build] Error 2
make: *** [Makefile:234: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.5.0-35-generic'

**Comment by sschamp** [comment]
I ended up installing Ubuntu 22.04.1 and updating grub to load the 5.x kernel.
Script worked fine then, thanks!
